name: checks

on:
  pull_request:
    paths:
      - 'builder/*.py'

jobs:
  python-type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r builder/requirements.txt

      - name: Run mypy on builder/cheat-sheet.py
        run: |
          mypy \
            --disallow-untyped-defs \
            --disallow-incomplete-defs \
            --check-untyped-defs \
            --warn-unused-ignores \
            --warn-return-any \
            builder/cheat-sheet.py

  js-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt install jshint

      - name: Run builder/site/rsc/index.js check
        run: |
          jshint builder/site/rsc/index.js
